name: snackbar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  get: 4.6.4
  flutter_svg: ^1.1.5
  wc_form_validators: ^1.0.0
  introduction_screen: ^3.0.2
  badges: ^2.0.3
  adaptive_action_sheet: ^2.0.2
  sliding_up_panel: ^2.0.0+1
  dropdown_button2: ^1.8.9
  validatorless: ^1.2.3
  readmore: ^2.1.0
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.1
  time_range: ^1.0.3
  another_stepper: ^1.0.4
  dotted_border: ^2.0.0+3
  shadow: ^1.5.0
  intl: ^0.17.0
  get_cli: ^1.8.1
  url_launcher: ^6.1.7





  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"



flutter: 
  assets: 
    - assets/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins_Medium.ttf

  uses-material-design: true

